---
development:
  cloud_name: dasf7qxuf
  api_key: '458281774864292'
  api_secret: _Kpia2LPcbNyxtoZLN3H31Z3Lj0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dasf7qxuf
  api_key: '458281774864292'
  api_secret: _Kpia2LPcbNyxtoZLN3H31Z3Lj0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dasf7qxuf
  api_key: '458281774864292'
  api_secret: _Kpia2LPcbNyxtoZLN3H31Z3Lj0
  enhance_image_tag: true
  static_image_support: false
