# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: UTF8
  host: localhost
  port: 5432

development: &development
  <<: *default
  database: amazing_dev
  username: <%= Rails.application.secrets[:database][:user] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  host: localhost

test:
  <<: *default
  database: amazing_dev
  username: <%= Rails.application.secrets[:database][:user] %>
  password: <%= Rails.application.secrets[:database][:password] %>

production:
  <<: *default
  database: <%= ENV['AMAZING_DATABASE'] %>
  username: <%= ENV['AMAZING_DATABASE_USERNAME'] %>
  password: <%= ENV['AMAZING_DATABASE_PASSWORD'] %>
  host: <%= ENV['AMAZING_DATABASE_HOST'] %>
  port: <%= ENV['AMAZING_DATABASE_PORT'] %>

